name: Temporary export label images

on:
  push:
    branches:
      - label-batches

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload batch 23-26 images
        uses: actions/upload-artifact@v4
        with:
          name: label-images-23-26
          path: |
            label-batches/batch_23/images
            label-batches/batch_24/images
            label-batches/batch_25/images
            label-batches/batch_26/images
          retention-days: 1
